### ISSUE TITLE
Budget Tracker Improvements

### ISSUE THREAD

**Issue by ShadabFaiz** [FundImpact/fundimpact-frontend#113]
**Create Speerate PR for UI and Techincal Fix**

## UI
- [x] If there is no list available for Select, then show `No (context) available`, and it should be disabled.
- [x] Settings => Donors :1. Skeleton on loading.

## Technical
- [ ] Replaacce `any` with proper type. Keeps types in sperate file.
- [x] Remaining Test Cases.
- [ ] Added Proper description if any component is being used in multiple places.  Things that description should include are:
  1. What is component about.  
  2. An Example of input / output if possible.
  3. Any Special Case that is left out or is being handled?
